version: 2.1

orbs:
  node: circleci/node@4.6.0

jobs:
  build:
    executor:
      name: node/default
      tag: "12.22"
    steps:
      - checkout
      - node/install-npm:
          version: "8"
      - node/install-packages
      - run: npm test
